apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: challenge
spec:
  selector:
    app: app
  ports:
    - name: http
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: challenge
spec:
  replicas: 1
  selector:
    matchLabels: {app: app}
  template:
    metadata:
      labels: {app: app}
    spec:
      containers:
        - name: app
          image: mrdt102/devops-app:latest
          ports:
            - containerPort: 3000
          env:
            - {name: PORT, value: "3000"}
            - {name: DB_HOST, value: "mysql"}
            - {name: DB_PORT, value: "3306"}
            - {name: DB_USER, value: "root"}
            - {name: DB_PASS, value: "root"}
            - {name: DB_NAME, value: "devops_test"}
