apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: challenge
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: challenge
spec:
  replicas: 1
  selector:
    matchLabels: { app: mysql }
  template:
    metadata:
      labels: { app: mysql }
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - { name: MYSQL_ROOT_PASSWORD, value: "root" }
            - { name: MYSQL_DATABASE_NAME, value: "devops_test" }
          ports:
            - containerPort: 3306
          readinessProbe:
            exec: { command: ["sh","-lc","mysqladmin ping -h 127.0.0.1 --silent"] }
            initialDelaySeconds: 10
            periodSeconds: 5
